# Promises

[TOC]


<!-- ToDo: fix resolve != fulfill 

https://twitter.com/jaffathecake/status/1248179232775319559
https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md
https://jakearchibald.com/2014/resolve-not-opposite-of-reject/
-->

## Introduction

(see also beforehand Runtime environment)

- sync code is blocking, wants to continue and come back to long task only after it has finished
- "Synchronous programming is disrespectful and should not be employed in applications which are used by people." - Douglas Crockford
- run code async via Browser APIs to not block the code, e.g. Fetch API, setTimeout API, etc.
- "Async all the things!"
- problem: coordination of responses of two concurrent code paths, bring async code paths back together
- problem: later sync code that relys on previous async code breaks, because will run before any async code, needs way of knowing when async code is done, run async code like sync code
- solution 1: callback functions, old way
- solution 2: promise objects, new way (with ES6), some Browser APIs already use promises, e.g. Fetch API, Battery API, Service Worker API
- solution 3: `async` / `await`, just syntactical sugar on promises (with ES2017)



## Callbacks

- put all sync code relying on the async code in a callback function, and pass it as argument to the async function, which then calls the "callback" after its async operation has finished
- convention is to use first argument of callback function for any error
- callback function must include any error handling apart from success handling, often anonymous

```javascript
function asyncFunc(..., callback) {
  ...                      // async operation
  if (...) {               // on success
    callback(null, data);
  } else {                 // on error
    callback(error);
  }
}

asyncFunc(..., callbackFunc(error, data));
```

- problem: multiple consecutive asynchronous callbacks get messy, "callback hell", e.g. fetch image1, handle image1, upon success fetch image2, handle image2, etc.



## Promises

### Idea

- instead of providing a callback function, let the `asyncFunc()` return a placeholder value for the time being, a "promise" to supply the value in the future
- with the placeholder value can work more in a synchronous fashion ?????
- decouple callback from `asyncFunc()` call
- used mainly for async operations, but could be used for any operation

### Introduction

- promise: special object, two internal properties `[[state]]` and `[[result]]`, methods `then()`, `catch()`, `finally()`
- `[[state]]`: initially `"pending"`, changes to `"fulfilled"` if (async) operation was successful, or to `"rejected"` if not, (see later how it determines this), (beware: "resolve" is the process of determining the state)
- `[[result]]`: initially `undefined`, changes to success value if (async) operation was successful, or to error value if not, (see later how it determines this)
- `then(callbackOnSuccess, callbackOnError)`: attaches callback function to promise object
  - when promise "settles" (i.e. changes `[[state]]`) the first or second callback function is called accordingly depending on `[[state]]`
  - the argument to the callback is `[[result]]`, e.g. data or error
  - second argument is optional, then `then` only handles fulfillment
- `catch(callbackOnError)`: shorthand for `then(null, callbackOnError)`
- `finally(callbackAlways)`: like `then(f, f)` except callback is not passed any arguments when called, i.e. callback gets called no matter result (with ES2019)
- (actually `[[result]]` is named differently depending on the `[[state]]` of the promise, namely `[[value]]` for resolved promise and `[[reason]]` for rejected, and doesn't exist at all while promise is pending, but here distinction is not relevant and causes only confusion)

### Creating a promise

```javascript
new Promise(executor)
```

- constructor takes and runs an "executor" function, i.e. no parentheses, and returns immediately a new promise object
- executor gets called with two internal functions as arguments, typically names first `resolve` and second `reject`
- if the executor calls `resolve`, the `[[state]]` of the promise object becomes `resolved`, i.e. on successfully operation
- if the executor calls `reject`, the `[[state]]` of the promise object becomes `rejected`, i.e. on failed operation
- in both cases the _single_ argument passed in `resolve`/`reject` becomes the `[[result]]` of the promise object, can be any value, e.g. data or error
- a promise can change state (and result) only once, any further calls to `resolve`/`reject` in the executor are ignored ❗️
- when the promise object settles, all callback handlers attached to the promise object for its `[[state]]` (i.e. via `then`, `catch`, or `finally`) get called in order of attachement 
- any callback handler attached to the promise for its `[[state]]` after it already settled gets called immediately
- a callback handler is passed the `[[result]]` as _single_ argument
- a callback is called async via the microtask queue ❗️
- if any error is thrown in the executor, the promise directly becomes `rejected` with the error as `[[result]]`, even if it didn't call `resolve`/`reject` yet
- any return value of the executor itself is ignored

#### Variant 1: `asyncFunc()` is executor itself

```javascript
function asyncFunc(resolve, reject) {
  ...               // async operation
  if (...) {        // on success
    resolve(data);
  } else {          // on error
    reject(error);
  }
}

const p = new Promise(asyncFunc);
p.then(callbackOnSuccess(data), callbackOnError(error));
```

- `callbackOnSuccess`/`Error()` are often anonymous
- `asyncFunc()` can't be passed other arguments, since it is used as executor, i.e. can't give it parentheses with arguments in `Promise` constructor

#### Variant 2: `asyncFunc()` returns promise object

```javascript
function asyncFunc(...) {
  return new Promise(function(resolve, reject) {
    ...               // async operation
    if (...) {        // on success
      resolve(data);
    } else {          // on error
      reject(error);
    }
  });
}

const p = asyncFunc(...);
p.then(callbackOnSuccess(data), callbackOnError(error));
```

- `callbackOnSuccess`/`Error()` are often anonymous
- `asyncFunc()` can be passed other arguments, since it returns promise object created using anonymous function as executor
- better than Variant 1, more flexible

### Promise composition

- `then()` (i.e. also `catch()` and `finally()`) returns itself a new promise, enables chaining other `then()`s to it, "promise chain", e.g.

```javascript
p.then(callbackOnSuccess).catch(callbackOnError);
```

- if `then()` has no handler for the promise's state, it returns a new promise identical to its own which she is a method of, i.e. a result that can't be handled by the current block gets "passed" to next, e.g. error gets passed to closest error handler (i.e. `catch(cOE)` or `then(cOS, cOE)`)
- if `then()` has a handler for the promise's state, the returned value from the handler gets converted into a promise
  - if handler returns a promise itself, `then()` returns an identical promise
  - if handler returns a value, `then()` returns a _resolved_ promise with that value as `[[result]]`, i.e. `Promise.resolve(value)`
  - if handler throws any error, `then()` returns a _rejected_ promise with that error as `[[result]]`, i.e. `Promise.reject(error)`
  - if handler returns nothing, i.e. `undefined`, `then()` returns a _resolved_ promise with `[[result]]` being `undefined`, i.e. `Promise.resolve(undefined)`
- when `then()` attaches the callback handler to the promise, it stores a reference to the new promise it's going to return with it, such that when the callback is called later it's return value is taken to modify the promise `then()` has already returned ❓
- after a result found a suitable handler, the promise chain continues from there, i.e. handlers in between are "skipped"
- good practice to always include an error handler at end of promise chain apart from inital error handler for promise from `asyncFunc` to handle any errors thrown in handlers in promise chain itself
- don't nest promise handlers, since creates two independent racing chains, limits scope of error handler, only use single promise chain ⚠️

#### `Promise` object type

- `Promise.resolve(value)`: creates resolved promise with `value` as result
- `Promise.reject(reason)`: creates rejected promise with `reason` as result
- `Promise.all(iterable)`: creates _one_ promise based on all promises in `iterable`, e.g. `[p1, p2]`
  - fulfills if _all_ promises fulfill, with _array_ of `values` as result, with values being in same order as promises, independently of which promise fulfilled first
  - rejects as soon as first promise rejects, with `reason` as result, other promises continue to be executed but get ignored since created promise has already settled
  - non-promise values in iterable are directly passed into result array
  - -> can do multiple _independent_ async operations for which order still matters, e.g. loading images and appending to body
  - -> for multiple _dependent_ async operations needs to use promise chaining instead, e.g. fetch data1, based on data1 fetch data2
- `Promise.race(iterable)`: creates promise that fulfills / rejects as soon as first promise fulfills / rejects, with `value` or `error` as result

#### Summary

- a promise is an object with two internal properties that are determined by if the executor (function containing the async operation) calls its first or second argument which it is passed internally by the `Promise` constructor
- used as placeholder for a value that's not available yet
- takes care of calling all the right callback functions, can attach callbacks later, no hurry, don't need to know them when creating promise
- more graceful error handling than with async callbacks, all errors can be handled in one block, or multiple if prefers
- can attach multiple callbacks to same promise
- can chain multiple promises, no nesting needed 🎉
- only limitation: promise can be resolved only once, while a callback can be called as many times as necessary from async operation
- -> remember: all sync code relying on async code must go in callback function, since callbacks get run from microtask queue only after _all_ sync code is done ❗️
- -> every async function should return a promise, every async operation should be done in one link of a promise chain
- a promise is like an event target which emits a single "success" or "failure" event, can attach event handlers for the different events, event handlers attached after event happened get still called with event outcome



## Resources

- MDN - as usual
- [Michael Jackson - Redemption from Callback Hell](https://www.youtube.com/watch?v=hf1T_AONQJU)