# Promises



## Introduction

- object returned by Web API, can think of box that will contain a value in the future (with ES6)
- method to register callback, returns itself a promise, subsequential Web API calls are chained instead of nested üéâ
- method to register error callback, "skips" rest of chain automatically, first-class error handling üéâ
- chained functions have separate scopes, can't access variables from within different callbacks easily, needs to pass value along

- different queue, WHY?

can register handlers also later, result isn't lost, cached until registers, but still called async, shouldn't need to do but is possible
register method returns itself a promise
  if handler returns a promise just uses this promise, even in error handler !!
  if returns value then creates fulfilled promise using that value, even in error handler !!
  if throws value then creates rejected promise using that value, even in fulfilled handler !!
  -> handlers aren't treated differently for the resulting promise of their registration then() method !!
guarantees, because only onFulfilled or onRejected is called, and only called once

remember, that we are still async, needs to do the work inside some handler, any returned value from a handler "outside" (in between sync code) is always a promise, can have endless promise chain
the register methods ("outside") are executed synchronously, hooks up chain of callbacks internally, callbacks are called in corresponding microtask
outside: sync main code...
inside: async handler code...

```javascript
const u = doSync();
const n = u.n; // outside

const nPromise = doAsync().then(u => {
  return u.n; // inside
}) // outside is always promise
```

gives back a call stack, can return ?, can throw
guarantees, because only one handler is called and only once

separates input and output of API properly again
gets only one value (not multiple like arguments in callback handler)
only one handler will be called, either fulfilled or rejected, not both
  only once, not multiple times
can throw

promise handler is called async always since it uses queue, unlike callback which might get called synchronously since it's part of language already

promise chain should always end with a single error handler (which returns anything, like undefined, but never throws), because otherwise will stay rejected
and no one to catch it, "uncaught rejected promise" / "unhandled promise rejection" in console, runtime dies, logs uncaught error to console




///// old

<!-- ToDo:
rename "resolved" to "fulfilled"
"resolve()" isn't "fulfil()" (opposite of "reject()"), but the act of determining wheter it's fulfilled or rejected (like "compute"), since resolve() can create a fulfilled or rejected promise depending on input

also rename
[[PromiseState]] instead of [[state]], can be pending, fulfilled, rejected
[[PromiseValue]] instead of [[result]], can be ???

https://twitter.com/jaffathecake/status/1248179232775319559
https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md
https://jakearchibald.com/2014/resolve-not-opposite-of-reject/
-->

<!-- todo: add https://web.dev/promises/

maybe https://promisesaplus.com/ as precessor of Promsies

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
-->

/// detail
beware: resolve(something) rejects, if something is a promise that rejects, or if throws (because doesn't exist)
  can safely call resolve with another promise BUT NOT REJECT???
```javascript
new Promise(function(resolve, reject) {
  resolve(something);
})

Promise.resolve(Promise.reject());

Promise.resolve().then(function() {
  return Promise.reject();
});
```

## Promises

### Idea

- instead of providing a callback function, let the `asyncFunc()` return a placeholder value for the time being, a "promise" to supply the value in the future
- with the placeholder value can work more in a synchronous fashion ?????
- decouple callback from `asyncFunc()` call
- used mainly for async operations, but could be used for any operation

### Introduction

- promise: special object, two internal properties `[[state]]` and `[[result]]`, methods `then()`, `catch()`, `finally()`
- `[[state]]`: initially `"pending"`, changes to `"fulfilled"` if (async) operation was successful, or to `"rejected"` if not, (see later how it determines this), (beware: "resolve" is the process of determining the state)
- `[[result]]`: initially `undefined`, changes to success value if (async) operation was successful, or to error value if not, (see later how it determines this)
- `then(callbackOnSuccess, callbackOnError)`: attaches callback function to promise object
  - when promise "settles" (i.e. changes `[[state]]`) the first or second callback function is called accordingly depending on `[[state]]`
  - the argument to the callback is `[[result]]`, e.g. data or error
  - second argument is optional, then `then` only handles fulfillment
- `catch(callbackOnError)`: shorthand for `then(null, callbackOnError)`
- `finally(callbackAlways)`: like `then(f, f)` except callback is not passed any arguments when called, i.e. callback gets called no matter result (with ES2019)
- (actually `[[result]]` is named differently depending on the `[[state]]` of the promise, namely `[[value]]` for resolved promise and `[[reason]]` for rejected, and doesn't exist at all while promise is pending, but here distinction is not relevant and causes only confusion)

### Creating a promise

```javascript
new Promise(executor)
```

- constructor takes and runs an "executor" function, i.e. no parentheses, and returns immediately a new promise object
- executor gets called with two internal functions as arguments, typically names first `resolve` and second `reject`
- if the executor calls `resolve`, the `[[state]]` of the promise object becomes `resolved`, i.e. on successfully operation
- if the executor calls `reject`, the `[[state]]` of the promise object becomes `rejected`, i.e. on failed operation
- in both cases the _single_ argument passed in `resolve`/`reject` becomes the `[[result]]` of the promise object, can be any value, e.g. data or error
- a promise can change state (and result) only once, any further calls to `resolve`/`reject` in the executor are ignored ‚ùóÔ∏è
- when the promise object settles, all callback handlers attached to the promise object for its `[[state]]` (i.e. via `then`, `catch`, or `finally`) get called in order of attachement 
- any callback handler attached to the promise for its `[[state]]` after it already settled gets called immediately
- a callback handler is passed the `[[result]]` as _single_ argument
- a callback is called async via the microtask queue ‚ùóÔ∏è
- if any error is thrown in the executor, the promise directly becomes `rejected` with the error as `[[result]]`, even if it didn't call `resolve`/`reject` yet
- any return value of the executor itself is ignored

#### Variant 1: `asyncFunc()` is executor itself

```javascript
function asyncFunc(resolve, reject) {
  ...               // async operation
  if (...) {        // on success
    resolve(data);
  } else {          // on error
    reject(error);
  }
}

const p = new Promise(asyncFunc);
p.then(callbackOnSuccess(data), callbackOnError(error));
```

- `callbackOnSuccess`/`Error()` are often anonymous
- `asyncFunc()` can't be passed other arguments, since it is used as executor, i.e. can't give it parentheses with arguments in `Promise` constructor

#### Variant 2: `asyncFunc()` returns promise object

```javascript
function asyncFunc(...) {
  return new Promise(function(resolve, reject) {
    ...               // async operation
    if (...) {        // on success
      resolve(data);
    } else {          // on error
      reject(error);
    }
  });
}

const p = asyncFunc(...);
p.then(callbackOnSuccess(data), callbackOnError(error));
```

- `callbackOnSuccess`/`Error()` are often anonymous
- `asyncFunc()` can be passed other arguments, since it returns promise object created using anonymous function as executor
- better than Variant 1, more flexible

### Promise composition

- `then()` (i.e. also `catch()` and `finally()`) returns itself a new promise, enables chaining other `then()`s to it, "promise chain", e.g.

```javascript
p.then(callbackOnSuccess).catch(callbackOnError);
```

- if `then()` has no handler for the promise's state, it returns a new promise identical to its own which she is a method of, i.e. a result that can't be handled by the current block gets "passed" to next, e.g. error gets passed to closest error handler (i.e. `catch(cOE)` or `then(cOS, cOE)`)
- if `then()` has a handler for the promise's state, the returned value from the handler gets converted into a promise
  - if handler returns a promise itself, `then()` returns an identical promise
  - if handler returns a value, `then()` returns a _resolved_ promise with that value as `[[result]]`, i.e. `Promise.resolve(value)`
  - if handler throws any error, `then()` returns a _rejected_ promise with that error as `[[result]]`, i.e. `Promise.reject(error)`
  - if handler returns nothing, i.e. `undefined`, `then()` returns a _resolved_ promise with `[[result]]` being `undefined`, i.e. `Promise.resolve(undefined)`
- when `then()` attaches the callback handler to the promise, it stores a reference to the new promise it's going to return with it, such that when the callback is called later it's return value is taken to modify the promise `then()` has already returned ‚ùì
- after a result found a suitable handler, the promise chain continues from there, i.e. handlers in between are "skipped"
- good practice to always include an error handler at end of promise chain apart from inital error handler for promise from `asyncFunc` to handle any errors thrown in handlers in promise chain itself
- don't nest promise handlers, since creates two independent racing chains, limits scope of error handler, only use single promise chain ‚ö†Ô∏è

#### `Promise` object type

- `Promise.resolve(value)`: creates resolved promise with `value` as result
- `Promise.reject(reason)`: creates rejected promise with `reason` as result
- `Promise.all(iterable)`: creates (one!) promise that fulfills with value (as array of values of all promises) if all fulfill or rejects with error of first that rejects

based on all promises in `iterable`, e.g. `[p1, p2]`
  - fulfills if _all_ promises fulfill, with _array_ of `values` as result, with values being in same order as promises, independently of which promise fulfilled first
  - rejects as soon as first promise rejects, with `reason` as result, other promises continue to be executed but get ignored since created promise has already settled
  - non-promise values in iterable are directly passed into result array
  - -> can do multiple _independent_ async operations for which order still matters, e.g. loading images and appending to body
  - -> for multiple _dependent_ async operations needs to use promise chaining instead, e.g. fetch data1, based on data1 fetch data2
- `Promise.race(iterable)`: creates promise that fulfills / rejects as soon as first promise fulfills / rejects, with `value` or `error` as result
<!-- todo: add any, allSettled -->

- `Promise.any(iterable)`: creates promise that fulfills with value of first promise that fulfills or rejects with error (as array of errors of all promises) if all reject
  opposite of .all()
   (with ES????)
- `Promise.allSettled(iterable)`: (with ES????)



#### Summary

- a promise is an object with two internal properties that are determined by if the executor (function containing the async operation) calls its first or second argument which it is passed internally by the `Promise` constructor
- used as placeholder for a value that's not available yet
- takes care of calling all the right callback functions, can attach callbacks later, no hurry, don't need to know them when creating promise
- more graceful error handling than with async callbacks, all errors can be handled in one block, or multiple if prefers
- can attach multiple callbacks to same promise
- can chain multiple promises, no nesting needed üéâ
- only limitation: promise can be resolved only once, while a callback can be called as many times as necessary from async operation
- -> remember: all sync code relying on async code must go in callback function, since callbacks get run from microtask queue only after _all_ sync code is done ‚ùóÔ∏è
- -> every async function should return a promise, every async operation should be done in one link of a promise chain
- a promise is like an event target which emits a single "success" or "failure" event, can attach event handlers for the different events, event handlers attached after event happened get still called with event outcome
<!-- todo: promises != events
todo: move to events

event api is api that doesn't return value, no return value back in sync code, just schedules calls to the handler (possibly multiple times)
 -->



## Resources

- MDN - as usual